// Top ~200 US cities by population + common metro areas
// Used for client-side typeahead — no external API dependency
export const US_CITIES: string[] = [
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'Austin, TX',
  'San Jose, CA',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'Indianapolis, IN',
  'San Francisco, CA',
  'Seattle, WA',
  'Denver, CO',
  'Nashville, TN',
  'Oklahoma City, OK',
  'Washington, DC',
  'El Paso, TX',
  'Las Vegas, NV',
  'Boston, MA',
  'Portland, OR',
  'Louisville, KY',
  'Memphis, TN',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Mesa, AZ',
  'Sacramento, CA',
  'Atlanta, GA',
  'Kansas City, MO',
  'Omaha, NE',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Long Beach, CA',
  'Virginia Beach, VA',
  'Miami, FL',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tampa, FL',
  'Tulsa, OK',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Riverside, CA',
  'Corpus Christi, TX',
  'Lexington, KY',
  'Pittsburgh, PA',
  'Stockton, CA',
  'St. Paul, MN',
  'Cincinnati, OH',
  'Anchorage, AK',
  'Henderson, NV',
  'Greensboro, NC',
  'Plano, TX',
  'Newark, NJ',
  'Lincoln, NE',
  'Orlando, FL',
  'Irvine, CA',
  'Toledo, OH',
  'Jersey City, NJ',
  'Chula Vista, CA',
  'Durham, NC',
  'Laredo, TX',
  'Madison, WI',
  'St. Petersburg, FL',
  'Chandler, AZ',
  'Buffalo, NY',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Glendale, AZ',
  'Gilbert, AZ',
  'Winston-Salem, NC',
  'North Las Vegas, NV',
  'Norfolk, VA',
  'Chesapeake, VA',
  'Irving, TX',
  'Hialeah, FL',
  'Garland, TX',
  'Boise, ID',
  'Richmond, VA',
  'Spokane, WA',
  'Baton Rouge, LA',
  'Tacoma, WA',
  'San Bernardino, CA',
  'Modesto, CA',
  'Des Moines, IA',
  'Fontana, CA',
  'Moreno Valley, CA',
  'Santa Clarita, CA',
  'Fayetteville, NC',
  'Birmingham, AL',
  'Oxnard, CA',
  'Rochester, NY',
  'Port St. Lucie, FL',
  'Grand Rapids, MI',
  'Huntsville, AL',
  'Salt Lake City, UT',
  'Frisco, TX',
  'Yonkers, NY',
  'Amarillo, TX',
  'Glendale, CA',
  'Huntington Beach, CA',
  'McKinney, TX',
  'Montgomery, AL',
  'Augusta, GA',
  'Tempe, AZ',
  'Little Rock, AR',
  'Akron, OH',
  'Overland Park, KS',
  'Brownsville, TX',
  'Tallahassee, FL',
  'Mobile, AL',
  'Knoxville, TN',
  'Shreveport, LA',
  'Worcester, MA',
  'Newport News, VA',
  'Providence, RI',
  'Fort Lauderdale, FL',
  'Chattanooga, TN',
  'Oceanside, CA',
  'Garden Grove, CA',
  'Rancho Cucamonga, CA',
  'Santa Rosa, CA',
  'Sioux Falls, SD',
  'Ontario, CA',
  'Jackson, MS',
  'Elk Grove, CA',
  'Corona, CA',
  'Eugene, OR',
  'Pembroke Pines, FL',
  'Salem, OR',
  'Peoria, AZ',
  'Cary, NC',
  'Fort Collins, CO',
  'Lancaster, CA',
  'Palmdale, CA',
  'Hayward, CA',
  'Salinas, CA',
  'Springfield, MO',
  'Pomona, CA',
  'Macon, GA',
  'Savannah, GA',
  'Charleston, SC',
  'Naperville, IL',
  'Bridgeport, CT',
  'Pasadena, TX',
  'Joliet, IL',
  'Paterson, NJ',
  'Rockford, IL',
  'Killeen, TX',
  'McAllen, TX',
  'Bellevue, WA',
  'Murfreesboro, TN',
  'Midland, TX',
  'Waco, TX',
  'Provo, UT',
  'Bend, OR',
  'Asheville, NC',
  'Boulder, CO',
  'Santa Fe, NM',
  'Ann Arbor, MI',
  'Greenville, SC',
  'Columbia, SC',
  'Wilmington, NC',
  'Dayton, OH',
  'Pensacola, FL',
  'Cedar Rapids, IA',
  'Gainesville, FL',
  'Round Rock, TX',
  'San Marcos, TX',
  'College Station, TX',
  'Denton, TX',
  'Tyler, TX',
  'Beaumont, TX',
];

export function searchCities(query: string, limit = 6): string[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return US_CITIES
    .filter(city => city.toLowerCase().includes(q))
    .slice(0, limit);
}
